Fixes to MatrixEsp32Hub75Refresh*Impl.h required for C++20 compilation.
i2s_parallel_config_t is initialized with the C99/GNU designated member
initializers and old-style positional initializations. As of C++20, mixing
like this is no longer allowed.

The error is pretty self-explanatory:
src/MatrixEsp32Hub75Refresh_NT_Impl.h:449:9: error: either all initializer clauses should be designated or none of them should be

Tested working withe ESP32 HUB75 Matrix in NightDriverLED/Mesmerizer.